### ISSUE TITLE
上書きプロット回数を実行時に決めたい

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#1]
例えば、標準入力から整数値を読み込んでプロット回数に設定したいのですが、どのように記述するのがスマートでしょうか。
forループで書こうしたところコンパイルエラーになったので、下プログラムのように再帰関数を使いましたが、もっと簡単な記述があるのでしょうか。
C++は不慣れなもので、簡単な質問だったら申し訳ないですが、よろしくお願いします。

※日本語でissueを書きましたが、英語の方がよければ立て直します。

``` c++
#include <ADAPT/GPM2/GPMCanvas.h>
#include <iostream>
#include <string>
using namespace adapt::gpm2;

detail::GPMPlotBuffer2D<detail::GPMGraphParam2D> SuccessivePlot(GPMCanvas2D& g,  int n) {
	std::string eq = std::to_string(n) + "*x";
	if (n == 1){
		return g.PlotPoints(eq, plot::title = eq, plot::style = Style::lines);
	}
	return SuccessivePlot(g, n-1).PlotPoints(eq, plot::title = eq, plot::style = Style::lines);
}

// 標準入力から n(>=1) を取得し、y=x,  y= 2x, ...,  y=nx を重ねて描画
int main() {
	std::string equation = "x";
	GPMCanvas2D g("example.png");

	int n;
	std::cout << "繰り返し数を入力 > ";
	std::cin >> n;
	if (std::cin.fail() || n<1 )
		return -1;
	SuccessivePlot(g, n);
}
```

**Comment by thayakawa-gh** [comment]
ライブラリをご利用いただきありがとうございます。他者に利用してもらうのは初めてなので、少し舞い上がっています。

申し訳ないのですが、この使い方は想定できていませんでした。プロットされる関数等の数が一定であることを前提に、Plot系関数を連結して呼び出すように設計していたのです。とはいえ、可変個の関数に対応すること自体は貴方も行っているように不可能ではありません。

既にソースコードを読まれたかもしれませんが、PlotPoints関数はdetail::GPMPlotBuffer2D<detail::GPMGraphParam2D>にプロット情報を蓄積し、破棄される時（デストラクタが呼ばれる時）に蓄積された情報を一気にGnuplotへ出力します。したがって、Bufferオブジェクトを上手く使い回している再帰関数は一つの良い方法ではあります。

敢えてforループで回したいのでしたら、お使いのバージョンでは少々小技が必要なのですが、例えば次のようにstd::optionalを使う方法があります。コンパイルエラーは代入演算子が削除されていることが原因だと考えられるので、std::optional::emplaceを用いることで代入演算子ではなくムーブコンストラクタを呼んでやれば良いのです。もしC++17を利用できないのでしたら、代わりにstd::unique_ptrなどを用いても同様のことを実現できます。
```cpp
#include <ADAPT/GPM2/GPMCanvas.h>
#include <iostream>
#include <string>
#include <optional>

using namespace adapt::gpm2;

// 標準入力から n(>=1) を取得し、y=x,  y= 2x, ...,  y=nx を重ねて描画
int example_for_loop() {
	std::string equation = "x";
	GPMCanvas2D g("example.png");

	int n;
	std::cout << "繰り返し数を入力 > ";
	std::cin >> n;
	if (std::cin.fail() || n < 1)
		return -1;

	//最初の一度だけはBufferではなくGPMCanvas2Dに対してPlotPointsを呼ぶ必要がある。
	std::string eq = std::to_string(0) + "*x";
	std::optional<GPMCanvas2D::_Buffer> buf = g.PlotPoints(eq, plot::title = eq, plot::style = Style::lines);
	for (int i = 1; i < n; ++i)
	{
		std::string eq = std::to_string(i) + "*x";
		buf.emplace(buf->PlotPoints(eq, plot::title = eq, plot::style = Style::lines));
	}
	buf.reset();//resetを呼ぶことでBufferオブジェクトのデストラクタが呼ばれ、プロットコマンドが実行される。
}
```

また折角ですし、もう少しだけスマートに書けるようにアップデートしてみました。詳細は最新バージョンのADAPT-GPM2と[example_for_loop.h](https://github.com/thayakawa-gh/ADAPT-GPM2/blob/master/examples/example_for_loop.h)を参照してください。std::optionalや一度目のGPMCanvas2D::PlotPointsの呼び出しが不要になるよう改良してあります。

**Comment by estshorter** [comment]
コードの提示と修正ありがとうございます。
特に、コードの方は大変参考になりました。

> ライブラリをご利用いただきありがとうございます。他者に利用してもらうのは初めてなので、少し舞い上がっています。

こちらこそ、使いやすいライブラリを公開していただいてありがとうございます。
C++でグラフ描画をするにあたって色々なライブラリを検討したのですが、個人的にはGPM2が一番しっくりきたので使用している次第です。
