### ISSUE TITLE
【要望】一時ファイルなしでのグラフ描画

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#10]
現状、`GraphParam::DATA`に対しては、データを一旦ファイルに書き出したのちgnuplotで描画するという仕様となっています。この一時ファイル作成ですが、市販のウイルス対策ソフト（ウイルスバスター）が入っている環境では、ウイルスチェックのためかやたらと（ちゃんと計測していませんが、体感数秒程度）時間がかかってしまいます。
このため、一時ファイルなしで描画する機能が実装されると動作速度の観点から非常に助かります。
（ウイルス対策ソフトを変えるという案が最も簡単なのですが、会社のPCなのでなかなか難しく、、

具体的な実装としては、gnuplot 5.2より導入されたinline dataやdatablocks（[マニュアル](http://www.gnuplot.info/docs_5.2/Gnuplot_5.2.pdf)のp.38-39 "inline data and datablocks"の節を参照）を使えば実現できるのではと思っています。

追記：
ウイルスバスター環境下での実行時間について計測してみたところ、一時ファイル作成でなく、`_popen()`の実行に時間がかかる**ことがある**ようです。参考まで。

**Comment by thayakawa-gh** [comment]
こんな機能が実装されていたとは知りませんでした……。一時ファイルの生成については私も疑問に思うところではあったので、実現可能かどうか少し検証してみます。
