### ISSUE TITLE
Template.hでtupleをincludeしていない

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#12]
私の環境では、以下の手順を実行するとコンパイルエラーとなります。

1. Visual Studioで新しい空C++プロジェクトを作成
2. インクルードディレクトリを設定し、ADAPT-GPM2を読みこめるようにする
3. コマンドラインオプションに`/utf-8 /Zc:__cplusplus`  を追加
4. 以下の内容をコンパイル

``` cpp
#include <ADAPT/GPM2/GPMCanvas.h>

using namespace adapt::gpm2;

int main()
{
	GPMCanvas2D g("test.png");
	g.PlotPoints("exp(-x*x/2)");
}
```

## エラー内容
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	C2039	'tuple_cat': 'std' のメンバーではありません	hoge	C:\Users\estshorter\source\repos\hoge\include\ADAPT\CUF\Template.h	496	
エラー	C2039	'forward_as_tuple': 'std' のメンバーではありません	hoge	C:\Users\estshorter\source\repos\hoge\include\ADAPT\CUF\Template.h	496	
```
`Template.h`で`#include <tuple>`していないことが原因だと思われ、includeすればコンパイルに成功します。

ちなみに、C++のバージョン(C++言語標準）をC++17に設定すると何故かエラーが出なくなります。

## 環境
- Win10 20H2
- Visual Studio Community 2019 16.8.2

**Comment by thayakawa-gh** [comment]
すみません、手元の方では修正済みだったのですが、反映するのを忘れていました。報告ありがとうございます、後ほど修正します。
