### ISSUE TITLE
-Zc:__cplusplusオプションの必要性について

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#13]
008962fad6ff1ccf0ade21769ced1cc135ba36b1 より、Visual StudioでADAPT-GPM2をコンパイルする際には`-Zc:__cplusplus`オプションの設定が必須となっています。
```_MSVC_LANG```マクロを`Function.h`中で以下のように使えば`-Zc:__cplusplus`を設定しなくて済みます(※)が、現状の設定は何か意図があるのでしょうか。VSプロジェクトを作るたびに`-Zc:__cplusplus`を設定するのは多少ではありますが手間なのでお聞きした次第です。

``` cpp
#if __cplusplus >= 201703L || (defined(_MSVC_LANG) && _MSVC_LANG  >= 201703L)
	constexpr bool L1 = std::is_lvalue_reference<Array1>::value;
	constexpr bool L2 = std::is_lvalue_reference<Array2>::value;
	return std::array<Type, N1 + N2>{ Forward<!L1>(a[Indices1])..., Forward<!L2>(b[Indices2])... };
#elif __cplusplus >= 201402L || (defined(_MSVC_LANG) && _MSVC_LANG  >= 201402L)
	return std::array<Type, N1 + N2>{ static_cast<const std::remove_reference_t<Array1>&>(a)[Indices1]...,
									  static_cast<const std::remove_reference_t<Array2>&>(b)[Indices2]... };
#endif
```

(※)参考1.に挙げたVisual Studioリファレンスによれば、
> When /Zc:__cplusplus is enabled, __cplusplus == _MSVC_LANG.

です。
## 参考
1. [/Zc:__cplusplus (Enable updated __cplusplus macro)
](https://docs.microsoft.com/ja-jp/cpp/build/reference/zc-cplusplus?view=msvc-160)
2. [Predefined macros](https://docs.microsoft.com/ja-jp/cpp/preprocessor/predefined-macros?view=msvc-160)

**Comment by thayakawa-gh** [comment]
いえ、単に私が_MSVC_LANGというマクロを知らなかっただけです……。確かにこちらのほうが手間は減りますね。  
ただ実を言うと、C++14への対応を打ち切ろうかと悩んでいるところです。各コンパイラがC++17への対応を終えてからそれなりに時間が経っていますし、そろそろ移行しても問題ないだろうと思っています。ただしMSVCの場合、プロジェクトを作成するたびに言語設定をC++17に切り替えなければならなくなるので、手間としてはあまり改善しません。  
C++14対応を維持して_MSVC_LANGを使うか、C++17に移行してマクロごと削除するか、どちらがよいでしょうか？

**Comment by estshorter** [comment]
回答ありがとうございます。

> C++14対応を維持して_MSVC_LANGを使うか、C++17に移行してマクロごと削除するか、どちらがよいでしょうか？

私個人としてはC++17移行の方が好ましいです。私は普段C++17で開発してますし、その方が@thayakawa-gh さんも開発しやすかろうと思いますので。

**Comment by thayakawa-gh** [comment]
遅くなってしまってすみません、非公開部分を含めたライブラリ全体で調整していたら想像以上に時間がかかってしまいました。
ひとまずC++17へ移行して当該マクロを削除しました。新たにEHscというオプションが加わっていますが、これはMSVCのプロジェクトではデフォルトで有効になっているので特に気にする必要はないはずです。
