### ISSUE TITLE
C4996 warning

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#3]
以下のコード（`std::getenv`）が原因でC4996 警告が出ます。
Visual studioプロジェクトだとエラーになるので一応報告しておきます。
（プロジェクトの設定を変えればコンパイル通りますが。

仕様ということでしたらcloseしていただいて構いません。

https://github.com/thayakawa-gh/ADAPT-GPM2/blob/c8a830fec838472085478af696c20dd511f0df6e/ADAPT/GPM2/GPMCanvas.h#L339

> C4996	'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

**Comment by thayakawa-gh** [comment]
これはstd::getenvに限らずMSVCで頻発する問題ですね。この警告を解消するためには非標準の関数を使わなければならず、私はあまり好ましいとは思いません。警告を無視してしまっても特に問題にはなりませんし、恐らくMSVCユーザーの大半は対処法を知っているでしょうから、ひとまず仕様ということでお願いします。
