### ISSUE TITLE
Build failure on GCC

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#6]
サポート対象外かもしれませんが、GCCでコンパイルすると警告&エラーが出ますので報告しておきます。添付ファイルの180行目以降がビルドログです。

以下のページの方が見やすいかもしれません。
https://github.com/estshorter/ADAPT-GPM2/actions/runs/167308358

## ビルド環境 (GitHub Actions)
- OS: Ubuntu 18.04
- Compiler: GCC 7.5

[1_build.txt](https://github.com/thayakawa-gh/ADAPT-GPM2/files/4912077/1_build.txt)

### 追記
Clangでも実行してみました。
https://github.com/estshorter/ADAPT-GPM2/actions/runs/167314336

**Comment by thayakawa-gh** [comment]
新たにブランチfix_to_build_with_gccを作成し、手元のGCC9.3.0で警告、エラーを起こさず正常に実行できるところまで修正しました。MSVCでやや警告が残っているので、それが修正でき次第masterへマージしようかと思います。
なおClangはこちらの手元に環境がないため試していません。また私は普段MSVCしか利用していないので、あまり継続的なサポートを期待しないようお願いします。

**Comment by estshorter** [comment]
対応ありがとうございます。
基本はMSVCのみをサポート、という点も承知しました。

**Comment by thayakawa-gh** [comment]
masterへマージしました。
