### ISSUE TITLE
return以降の式

### ISSUE THREAD

**Issue by estshorter** [thayakawa-gh/ADAPT-GPM2#8]
以下の関数について質問です。returnの後に式がありますが、これって意味あるのでしょうか？
意図的なのか単純ミスなのか判断がつかなかったので。

https://github.com/thayakawa-gh/ADAPT-GPM2/blob/1c4fcbf65892376cd97934066ad500805475990b/ADAPT/CUF/Function.h#L97-L104

### 追記
`std::is_convertible<const char*, std::string>::value; `を消してもexamplesのビルドは通りました。

**Comment by thayakawa-gh** [comment]
おっと、テスト的に書いたコードを消し忘れていたようです。指摘ありがとうございます。動作上はあってもなくても全く変わらないはずですが、削除しておきます。
